name: student_info_app
description: A Flutter app to display student info
publish_to: "none"

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true